// Actions for Portfolio Input
export const UPDATE_START_MONTH = 'UPDATE_START_MONTH';
export const UPDATE_START_YEAR = 'UPDATE_START_YEAR';
export const UPDATE_END_MONTH = 'UPDATE_END_MONTH';
export const UPDATE_END_YEAR = 'UPDATE_END_YEAR';
export const UPDATE_MONEY_INVESTED_IN_PERIOD = 'UPDATE_MONEY_INVESTED_IN_PERIOD';
export const UPDATE_INVESTMENT_BREAKDOWN = 'UPDATE_INVESTMENT_BREAKDOWN';
export const UPDATE_PORTFOLIO_VALUE = 'UPDATE_PORTFOLIO_VALUE';

// Actions for Fee Input
export const UPDATE_FEE_PERCENT_OF_PORTFOLIO = 'UPDATE_FEE_PERCENT_OF_PORTFOLIO';
export const UPDATE_FEE_FLAT_AMOUNT = 'UPDATE_FEE_FLAT_AMOUNT';
export const UPDATE_FEE_AVG_EXPENSE_RATIO = 'UPDATE_FEE_AVG_EXPENSE_RATIO';
